ALTER TABLE prize ADD COLUMN prize_type     VARCHAR(20)  NOT NULL DEFAULT 'PHYSICAL';
ALTER TABLE prize ADD COLUMN prize_category VARCHAR(30)  DEFAULT NULL;
ALTER TABLE prize ADD COLUMN title_image    VARCHAR(500) DEFAULT NULL;
ALTER TABLE prize ADD COLUMN detail_image   VARCHAR(500) DEFAULT NULL;
ALTER TABLE prize ADD COLUMN valid_from     TIMESTAMP    DEFAULT NULL;
ALTER TABLE prize ADD COLUMN valid_to       TIMESTAMP    DEFAULT NULL;
ALTER TABLE prize ADD COLUMN type_config    JSON         DEFAULT NULL;
