-- V2__auth_tables.sql
-- CuteGoals 2.0 认证相关表
-- 🔒 安全敏感任务

-- 账号表
CREATE TABLE IF NOT EXISTS account (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone           VARCHAR(20)     NOT NULL,
    password_hash   VARCHAR(255)    NOT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE account IS '账号表';
COMMENT ON COLUMN account.id IS '主键';
COMMENT ON COLUMN account.phone IS '手机号（唯一）';
COMMENT ON COLUMN account.password_hash IS '密码 bcrypt 哈希';
COMMENT ON COLUMN account.status IS '状态：ACTIVE/INACTIVE/DISABLED';
COMMENT ON COLUMN account.created_at IS '创建时间';
COMMENT ON COLUMN account.updated_at IS '更新时间';

CREATE UNIQUE INDEX uk_account_phone ON account (phone);

-- 角色绑定表
CREATE TABLE IF NOT EXISTS role_binding (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT          NOT NULL,
    role            VARCHAR(30)     NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_role_binding_account FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE
);
COMMENT ON TABLE role_binding IS '角色绑定表';
COMMENT ON COLUMN role_binding.id IS '主键';
COMMENT ON COLUMN role_binding.account_id IS '账号 ID';
COMMENT ON COLUMN role_binding.role IS '角色：INSTANCE_ADMIN/PARENT/CHILD';
COMMENT ON COLUMN role_binding.created_at IS '创建时间';

CREATE UNIQUE INDEX uk_role_binding_account_role ON role_binding (account_id, role);
CREATE INDEX idx_role_binding_account ON role_binding (account_id);
CREATE INDEX idx_role_binding_role ON role_binding (role);

-- 初始化令牌表
CREATE TABLE IF NOT EXISTS initialization_token (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash      VARCHAR(255)    NOT NULL,
    consumed        BOOLEAN         NOT NULL DEFAULT FALSE,
    expires_at      TIMESTAMP       NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE initialization_token IS '初始化令牌表';
COMMENT ON COLUMN initialization_token.id IS '主键';
COMMENT ON COLUMN initialization_token.token_hash IS '初始化令牌哈希';
COMMENT ON COLUMN initialization_token.consumed IS '是否已消费';
COMMENT ON COLUMN initialization_token.expires_at IS '过期时间';
COMMENT ON COLUMN initialization_token.created_at IS '创建时间';

CREATE UNIQUE INDEX uk_init_token_hash ON initialization_token (token_hash);
CREATE INDEX idx_init_token_consumed ON initialization_token (token_hash, consumed);

-- 会话表
CREATE TABLE IF NOT EXISTS session (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id          VARCHAR(128)    NOT NULL UNIQUE,
    account_id          BIGINT          NOT NULL,
    expires_at          TIMESTAMP       NOT NULL,
    device_fingerprint  VARCHAR(255)    DEFAULT NULL,
    revoked             BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_session_account FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE
);
COMMENT ON TABLE session IS '会话表';
COMMENT ON COLUMN session.id IS '主键';
COMMENT ON COLUMN session.session_id IS '会话 ID（UUID）';
COMMENT ON COLUMN session.account_id IS '账号 ID';
COMMENT ON COLUMN session.expires_at IS '过期时间';
COMMENT ON COLUMN session.device_fingerprint IS '设备指纹';
COMMENT ON COLUMN session.revoked IS '是否已撤销';
COMMENT ON COLUMN session.created_at IS '创建时间';
CREATE INDEX idx_session_account ON session (account_id);
CREATE INDEX idx_session_expires ON session (expires_at);

-- 刷新令牌表（支持家族链撤销）
CREATE TABLE IF NOT EXISTS refresh_token (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash      VARCHAR(255)    NOT NULL,
    session_id      VARCHAR(128)    NOT NULL,
    family_id       VARCHAR(128)    DEFAULT NULL,
    expires_at      TIMESTAMP       NOT NULL,
    revoked         BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_token_session FOREIGN KEY (session_id) REFERENCES session (session_id) ON DELETE CASCADE
);
COMMENT ON TABLE refresh_token IS '刷新令牌表';
COMMENT ON COLUMN refresh_token.id IS '主键';
COMMENT ON COLUMN refresh_token.token_hash IS '刷新令牌哈希';
COMMENT ON COLUMN refresh_token.session_id IS '所属会话 ID';
COMMENT ON COLUMN refresh_token.family_id IS '令牌家族链 ID（用于链式撤销）';
COMMENT ON COLUMN refresh_token.expires_at IS '过期时间';
COMMENT ON COLUMN refresh_token.revoked IS '是否已撤销';
COMMENT ON COLUMN refresh_token.created_at IS '创建时间';

CREATE UNIQUE INDEX uk_refresh_token_hash ON refresh_token (token_hash);
CREATE INDEX idx_refresh_token_session ON refresh_token (session_id);
CREATE INDEX idx_refresh_token_family ON refresh_token (family_id);

-- 登录限流表
CREATE TABLE IF NOT EXISTS login_rate_limit (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier      VARCHAR(255)    NOT NULL,
    attempt_count   INT             NOT NULL DEFAULT 1,
    window_start    TIMESTAMP       NOT NULL,
    locked_until    TIMESTAMP       DEFAULT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE login_rate_limit IS '登录限流表';
COMMENT ON COLUMN login_rate_limit.id IS '主键';
COMMENT ON COLUMN login_rate_limit.identifier IS '限流标识（IP/手机号/账号）';
COMMENT ON COLUMN login_rate_limit.attempt_count IS '尝试次数';
COMMENT ON COLUMN login_rate_limit.window_start IS '限流窗口起始时间';
COMMENT ON COLUMN login_rate_limit.locked_until IS '锁定截止时间';
COMMENT ON COLUMN login_rate_limit.created_at IS '创建时间';
COMMENT ON COLUMN login_rate_limit.updated_at IS '更新时间';

CREATE INDEX idx_rate_limit_identifier ON login_rate_limit (identifier);
CREATE INDEX idx_rate_limit_window ON login_rate_limit (identifier, window_start);
