-- V3__family_tables.sql
-- CuteGoals 2.0 家庭与成员表

-- 家庭表（单实例唯一约束通过应用层保证）
CREATE TABLE IF NOT EXISTS family (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    DEFAULT NULL,
    avatar          VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE family IS '家庭表';
COMMENT ON COLUMN family.id IS '主键';
COMMENT ON COLUMN family.name IS '家庭名称';
COMMENT ON COLUMN family.avatar IS '家庭头像';
COMMENT ON COLUMN family.created_at IS '创建时间';
COMMENT ON COLUMN family.updated_at IS '更新时间';



-- 家庭成员表
CREATE TABLE IF NOT EXISTS family_member (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id       BIGINT          NOT NULL,
    account_id      BIGINT          NOT NULL,
    role            VARCHAR(30)     NOT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_family_member_family FOREIGN KEY (family_id) REFERENCES family (id) ON DELETE CASCADE,
    CONSTRAINT fk_family_member_account FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE
);
COMMENT ON TABLE family_member IS '家庭成员表';
COMMENT ON COLUMN family_member.id IS '主键';
COMMENT ON COLUMN family_member.family_id IS '家庭 ID';
COMMENT ON COLUMN family_member.account_id IS '账号 ID';
COMMENT ON COLUMN family_member.role IS '角色：PARENT/CHILD';
COMMENT ON COLUMN family_member.status IS '状态：ACTIVE/INACTIVE';
COMMENT ON COLUMN family_member.created_at IS '创建时间';
COMMENT ON COLUMN family_member.updated_at IS '更新时间';

CREATE UNIQUE INDEX uk_family_member ON family_member (family_id, account_id);
CREATE INDEX idx_family_member_account ON family_member (account_id);
CREATE INDEX idx_family_member_role ON family_member (family_id, role);

-- 孩子档案表
CREATE TABLE IF NOT EXISTS child_profile (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id       BIGINT          NOT NULL,
    nickname        VARCHAR(100)    NOT NULL,
    avatar          VARCHAR(500)    DEFAULT NULL,
    pin_hash        VARCHAR(255)    DEFAULT NULL,
    birth_year      INT             DEFAULT NULL,
    age_group       VARCHAR(20)     DEFAULT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    deleted_at      TIMESTAMP       DEFAULT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_child_family FOREIGN KEY (family_id) REFERENCES family (id) ON DELETE CASCADE
);
COMMENT ON TABLE child_profile IS '孩子档案表';
COMMENT ON COLUMN child_profile.id IS '主键';
COMMENT ON COLUMN child_profile.family_id IS '家庭 ID';
COMMENT ON COLUMN child_profile.nickname IS '昵称';
COMMENT ON COLUMN child_profile.avatar IS '头像 URL';
COMMENT ON COLUMN child_profile.pin_hash IS 'PIN 哈希';
COMMENT ON COLUMN child_profile.birth_year IS '出生年份（可选）';
COMMENT ON COLUMN child_profile.age_group IS '年龄段（可选）';
COMMENT ON COLUMN child_profile.status IS '状态：ACTIVE/INACTIVE/DELETED';
COMMENT ON COLUMN child_profile.deleted_at IS '删除时间（匿名化）';
COMMENT ON COLUMN child_profile.created_at IS '创建时间';
COMMENT ON COLUMN child_profile.updated_at IS '更新时间';

CREATE INDEX idx_child_family ON child_profile (family_id);
CREATE INDEX idx_child_status ON child_profile (family_id, status);

-- 家长邀请表
CREATE TABLE IF NOT EXISTS parent_invitation (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id           BIGINT          NOT NULL,
    inviter_id          BIGINT          NOT NULL,
    target_phone        VARCHAR(20)     NOT NULL,
    secret_hash         VARCHAR(255)    NOT NULL,
    status              VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    expires_at          TIMESTAMP       NOT NULL,
    idempotency_key     VARCHAR(128)    DEFAULT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invitation_family FOREIGN KEY (family_id) REFERENCES family (id) ON DELETE CASCADE,
    CONSTRAINT fk_invitation_inviter FOREIGN KEY (inviter_id) REFERENCES account (id) ON DELETE CASCADE
);
COMMENT ON TABLE parent_invitation IS '家长邀请表';
COMMENT ON COLUMN parent_invitation.id IS '主键';
COMMENT ON COLUMN parent_invitation.family_id IS '家庭 ID';
COMMENT ON COLUMN parent_invitation.inviter_id IS '邀请人账号 ID';
COMMENT ON COLUMN parent_invitation.target_phone IS '目标手机号';
COMMENT ON COLUMN parent_invitation.secret_hash IS '邀请秘密哈希';
COMMENT ON COLUMN parent_invitation.status IS '状态：PENDING/ACCEPTED/REJECTED/REVOKED/EXPIRED';
COMMENT ON COLUMN parent_invitation.expires_at IS '过期时间';
COMMENT ON COLUMN parent_invitation.idempotency_key IS '幂等键';
COMMENT ON COLUMN parent_invitation.created_at IS '创建时间';
COMMENT ON COLUMN parent_invitation.updated_at IS '更新时间';

CREATE INDEX idx_invitation_family ON parent_invitation (family_id);
CREATE INDEX idx_invitation_target ON parent_invitation (target_phone);
CREATE INDEX idx_invitation_status ON parent_invitation (family_id, status);
CREATE INDEX idx_invitation_idempotency ON parent_invitation (inviter_id, idempotency_key);

-- 设备绑定表
CREATE TABLE IF NOT EXISTS device_binding (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id           BIGINT          NOT NULL,
    device_id           VARCHAR(255)    NOT NULL,
    credential_hash     VARCHAR(255)    NOT NULL,
    status              VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    bound_by            BIGINT          NOT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_device_family FOREIGN KEY (family_id) REFERENCES family (id) ON DELETE CASCADE,
    CONSTRAINT fk_device_bound_by FOREIGN KEY (bound_by) REFERENCES account (id) ON DELETE CASCADE
);
COMMENT ON TABLE device_binding IS '设备绑定表';
COMMENT ON COLUMN device_binding.id IS '主键';
COMMENT ON COLUMN device_binding.family_id IS '家庭 ID';
COMMENT ON COLUMN device_binding.device_id IS '设备标识';
COMMENT ON COLUMN device_binding.credential_hash IS '绑定凭据哈希（不可从 API 读取）';
COMMENT ON COLUMN device_binding.status IS '状态：ACTIVE/REVOKED';
COMMENT ON COLUMN device_binding.bound_by IS '授权家长账号 ID';
COMMENT ON COLUMN device_binding.created_at IS '创建时间';
COMMENT ON COLUMN device_binding.updated_at IS '更新时间';

CREATE UNIQUE INDEX uk_device_binding ON device_binding (family_id, device_id);
CREATE INDEX idx_device_binding_status ON device_binding (family_id, status);
