-- V4__task_template_and_assignment_tables.sql
-- CuteGoals 2.0 任务模板与分配表

-- 任务模板表
CREATE TABLE IF NOT EXISTS task_template (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id       BIGINT          NOT NULL,
    name            VARCHAR(100)    NOT NULL,
    description     VARCHAR(2000)   DEFAULT NULL,
    icon            VARCHAR(500)    DEFAULT NULL,
    category        VARCHAR(50)     NOT NULL,
    version         INT             NOT NULL DEFAULT 1,
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP       DEFAULT NULL,
    deleted_by      BIGINT          DEFAULT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_template_family FOREIGN KEY (family_id) REFERENCES family (id) ON DELETE CASCADE
);
COMMENT ON TABLE task_template IS '任务模板表';
COMMENT ON COLUMN task_template.id IS '主键';
COMMENT ON COLUMN task_template.family_id IS '家庭 ID';
COMMENT ON COLUMN task_template.name IS '模板名称';
COMMENT ON COLUMN task_template.description IS '模板说明';
COMMENT ON COLUMN task_template.icon IS '图标标识';
COMMENT ON COLUMN task_template.category IS '分类';
COMMENT ON COLUMN task_template.version IS '版本号（乐观锁）';
COMMENT ON COLUMN task_template.enabled IS '是否启用';
COMMENT ON COLUMN task_template.deleted IS '是否逻辑删除';
COMMENT ON COLUMN task_template.deleted_at IS '删除时间';
COMMENT ON COLUMN task_template.deleted_by IS '删除人';
COMMENT ON COLUMN task_template.created_at IS '创建时间';
COMMENT ON COLUMN task_template.updated_at IS '更新时间';

CREATE INDEX idx_template_family ON task_template (family_id);
CREATE INDEX idx_template_category ON task_template (family_id, category);
CREATE INDEX idx_template_status ON task_template (family_id, enabled, deleted);

-- 任务难度表
CREATE TABLE IF NOT EXISTS task_difficulty (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id     BIGINT          NOT NULL,
    name            VARCHAR(50)     NOT NULL,
    display_order   INT             NOT NULL,
    reward_points   INT             NOT NULL,
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_difficulty_template FOREIGN KEY (template_id) REFERENCES task_template (id) ON DELETE CASCADE
);
COMMENT ON TABLE task_difficulty IS '任务难度表';
COMMENT ON COLUMN task_difficulty.id IS '主键';
COMMENT ON COLUMN task_difficulty.template_id IS '模板 ID';
COMMENT ON COLUMN task_difficulty.name IS '难度名称';
COMMENT ON COLUMN task_difficulty.display_order IS '展示顺序';
COMMENT ON COLUMN task_difficulty.reward_points IS '奖励积分（正整数）';
COMMENT ON COLUMN task_difficulty.enabled IS '是否启用';
COMMENT ON COLUMN task_difficulty.created_at IS '创建时间';
COMMENT ON COLUMN task_difficulty.updated_at IS '更新时间';

CREATE UNIQUE INDEX uk_difficulty_template_name ON task_difficulty (template_id, name);
CREATE UNIQUE INDEX uk_difficulty_template_order ON task_difficulty (template_id, display_order);
CREATE INDEX idx_difficulty_template ON task_difficulty (template_id);

-- 周期规则表
CREATE TABLE IF NOT EXISTS task_recurrence_rule (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id         BIGINT          NOT NULL,
    rule_type           VARCHAR(20)     NOT NULL,
    custom_weekdays     VARCHAR(20)     DEFAULT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recurrence_template FOREIGN KEY (template_id) REFERENCES task_template (id) ON DELETE CASCADE
);
COMMENT ON TABLE task_recurrence_rule IS '周期规则表';
COMMENT ON COLUMN task_recurrence_rule.id IS '主键';
COMMENT ON COLUMN task_recurrence_rule.template_id IS '模板 ID（一对一）';
COMMENT ON COLUMN task_recurrence_rule.rule_type IS '规则类型：DAILY/WEEKDAYS/WEEKENDS/CUSTOM_WEEKDAYS';
COMMENT ON COLUMN task_recurrence_rule.custom_weekdays IS '自定义星期集合（如 1,3,5）';
COMMENT ON COLUMN task_recurrence_rule.created_at IS '创建时间';
COMMENT ON COLUMN task_recurrence_rule.updated_at IS '更新时间';

CREATE UNIQUE INDEX uk_recurrence_template ON task_recurrence_rule (template_id);

-- 任务分配表（含快照字段）
CREATE TABLE IF NOT EXISTS task_assignment (
    id                              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id                       BIGINT          NOT NULL,
    template_id                     BIGINT          NOT NULL,
    child_id                        BIGINT          NOT NULL,
    difficulty_id                   BIGINT          DEFAULT NULL,
    deadline                        TIMESTAMP       NOT NULL,
    status                          VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    late_policy                     VARCHAR(10)     NOT NULL DEFAULT 'REJECT',
    cancelled                       BOOLEAN         NOT NULL DEFAULT FALSE,
    cancelled_at                    TIMESTAMP       DEFAULT NULL,
    cancelled_reason                VARCHAR(1000)   DEFAULT NULL,
    cancelled_by                    BIGINT          DEFAULT NULL,
    version                         INT             NOT NULL DEFAULT 1,
    idempotency_key                 VARCHAR(128)    DEFAULT NULL,
    occurrence_key                  VARCHAR(128)    DEFAULT NULL,
    snapshot_template_name          VARCHAR(100)    NOT NULL,
    snapshot_template_description   VARCHAR(2000)   DEFAULT NULL,
    snapshot_template_category      VARCHAR(50)     NOT NULL,
    snapshot_template_icon          VARCHAR(500)    DEFAULT NULL,
    snapshot_difficulty_name        VARCHAR(50)     NOT NULL,
    snapshot_difficulty_reward      INT             NOT NULL,
    created_at                      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_assignment_family FOREIGN KEY (family_id) REFERENCES family (id) ON DELETE CASCADE,
    CONSTRAINT fk_assignment_template FOREIGN KEY (template_id) REFERENCES task_template (id) ON DELETE CASCADE,
    CONSTRAINT fk_assignment_child FOREIGN KEY (child_id) REFERENCES child_profile (id) ON DELETE CASCADE
);
COMMENT ON TABLE task_assignment IS '任务分配表';
COMMENT ON COLUMN task_assignment.id IS '主键';
COMMENT ON COLUMN task_assignment.family_id IS '家庭 ID';
COMMENT ON COLUMN task_assignment.template_id IS '模板 ID';
COMMENT ON COLUMN task_assignment.child_id IS '孩子 ID';
COMMENT ON COLUMN task_assignment.difficulty_id IS '难度 ID';
COMMENT ON COLUMN task_assignment.deadline IS '截止时间';
COMMENT ON COLUMN task_assignment.status IS '状态：PENDING/SUBMITTED/APPROVED/REJECTED/COMPLETED';
COMMENT ON COLUMN task_assignment.late_policy IS '迟交策略：ALLOW/REJECT';
COMMENT ON COLUMN task_assignment.cancelled IS '是否取消';
COMMENT ON COLUMN task_assignment.cancelled_at IS '取消时间';
COMMENT ON COLUMN task_assignment.cancelled_reason IS '取消原因';
COMMENT ON COLUMN task_assignment.cancelled_by IS '取消人';
COMMENT ON COLUMN task_assignment.version IS '版本号（乐观锁）';
COMMENT ON COLUMN task_assignment.idempotency_key IS '幂等键';
COMMENT ON COLUMN task_assignment.occurrence_key IS '周期发生键（家庭+孩子+模板+日期）';
COMMENT ON COLUMN task_assignment.snapshot_template_name IS '快照-模板名称';
COMMENT ON COLUMN task_assignment.snapshot_template_description IS '快照-模板说明';
COMMENT ON COLUMN task_assignment.snapshot_template_category IS '快照-模板分类';
COMMENT ON COLUMN task_assignment.snapshot_template_icon IS '快照-模板图标';
COMMENT ON COLUMN task_assignment.snapshot_difficulty_name IS '快照-难度名称';
COMMENT ON COLUMN task_assignment.snapshot_difficulty_reward IS '快照-奖励积分';
COMMENT ON COLUMN task_assignment.created_at IS '创建时间';
COMMENT ON COLUMN task_assignment.updated_at IS '更新时间';

CREATE UNIQUE INDEX uk_assignment_occurrence ON task_assignment (family_id, child_id, occurrence_key);
CREATE INDEX idx_assignment_family ON task_assignment (family_id);
CREATE INDEX idx_assignment_child ON task_assignment (child_id);
CREATE INDEX idx_assignment_status ON task_assignment (status);
CREATE INDEX idx_assignment_deadline ON task_assignment (deadline);
CREATE INDEX idx_assignment_idempotency ON task_assignment (family_id, idempotency_key);

-- 任务分配快照表（历史版本追踪）
CREATE TABLE IF NOT EXISTS task_assignment_snapshot (
    id                          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id               BIGINT          NOT NULL,
    template_name               VARCHAR(100)    NOT NULL,
    template_description        VARCHAR(2000)   DEFAULT NULL,
    template_category           VARCHAR(50)     NOT NULL,
    template_icon               VARCHAR(500)    DEFAULT NULL,
    difficulty_name             VARCHAR(50)     NOT NULL,
    difficulty_reward_points    INT             NOT NULL,
    created_at                  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_snapshot_assignment FOREIGN KEY (assignment_id) REFERENCES task_assignment (id) ON DELETE CASCADE
);
COMMENT ON TABLE task_assignment_snapshot IS '任务分配快照表（不可变）';
COMMENT ON COLUMN task_assignment_snapshot.id IS '主键';
COMMENT ON COLUMN task_assignment_snapshot.assignment_id IS '分配 ID';
COMMENT ON COLUMN task_assignment_snapshot.template_name IS '模板名称';
COMMENT ON COLUMN task_assignment_snapshot.template_description IS '模板说明';
COMMENT ON COLUMN task_assignment_snapshot.template_category IS '模板分类';
COMMENT ON COLUMN task_assignment_snapshot.template_icon IS '模板图标';
COMMENT ON COLUMN task_assignment_snapshot.difficulty_name IS '难度名称';
COMMENT ON COLUMN task_assignment_snapshot.difficulty_reward_points IS '奖励积分';
COMMENT ON COLUMN task_assignment_snapshot.created_at IS '创建时间';

CREATE UNIQUE INDEX uk_snapshot_assignment ON task_assignment_snapshot (assignment_id);
