-- V5__submission_and_review_tables.sql
-- CuteGoals 2.0 提交与审核表
-- 不可变表（无 updated_at，无触发器）

-- 任务提交尝试表（不可变）
CREATE TABLE IF NOT EXISTS task_attempt (
    id                      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id           BIGINT          NOT NULL,
    child_id                BIGINT          NOT NULL,
    attempt_number          INT             NOT NULL,
    content                 VARCHAR(2000)   DEFAULT NULL,
    attachments             TEXT            DEFAULT NULL,
    submitted_at            TIMESTAMP       NOT NULL,
    is_late                 BOOLEAN         NOT NULL DEFAULT FALSE,
    late_policy_applied     VARCHAR(10)     NOT NULL,
    idempotency_key         VARCHAR(128)    DEFAULT NULL,
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attempt_assignment FOREIGN KEY (assignment_id) REFERENCES task_assignment (id) ON DELETE CASCADE,
    CONSTRAINT fk_attempt_child FOREIGN KEY (child_id) REFERENCES child_profile (id) ON DELETE CASCADE
);
COMMENT ON TABLE task_attempt IS '任务提交尝试表（不可变）';
COMMENT ON COLUMN task_attempt.id IS '主键';
COMMENT ON COLUMN task_attempt.assignment_id IS '分配 ID';
COMMENT ON COLUMN task_attempt.child_id IS '孩子 ID';
COMMENT ON COLUMN task_attempt.attempt_number IS '尝试序号（按孩子+分配递增）';
COMMENT ON COLUMN task_attempt.content IS '提交说明';
COMMENT ON COLUMN task_attempt.attachments IS '佐证引用 JSON（最多 10 个）';
COMMENT ON COLUMN task_attempt.submitted_at IS '提交时间';
COMMENT ON COLUMN task_attempt.is_late IS '是否迟交';
COMMENT ON COLUMN task_attempt.late_policy_applied IS '当时有效的迟交策略';
COMMENT ON COLUMN task_attempt.idempotency_key IS '请求幂等键';
COMMENT ON COLUMN task_attempt.created_at IS '创建时间';

CREATE UNIQUE INDEX uk_attempt_assignment_seq ON task_attempt (assignment_id, child_id, attempt_number);
CREATE UNIQUE INDEX uk_attempt_idempotency ON task_attempt (child_id, idempotency_key);
CREATE INDEX idx_attempt_assignment ON task_attempt (assignment_id);
CREATE INDEX idx_attempt_child ON task_attempt (child_id);

-- 任务审核记录表（不可变）
CREATE TABLE IF NOT EXISTS task_review (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id          BIGINT          NOT NULL,
    assignment_id       BIGINT          NOT NULL,
    reviewer_id         BIGINT          NOT NULL,
    decision            VARCHAR(10)     NOT NULL,
    reason              VARCHAR(1000)   DEFAULT NULL,
    idempotency_key     VARCHAR(128)    DEFAULT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_attempt FOREIGN KEY (attempt_id) REFERENCES task_attempt (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_assignment FOREIGN KEY (assignment_id) REFERENCES task_assignment (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_reviewer FOREIGN KEY (reviewer_id) REFERENCES account (id) ON DELETE CASCADE
);
COMMENT ON TABLE task_review IS '任务审核记录表（不可变）';
COMMENT ON COLUMN task_review.id IS '主键';
COMMENT ON COLUMN task_review.attempt_id IS '提交尝试 ID';
COMMENT ON COLUMN task_review.assignment_id IS '分配 ID';
COMMENT ON COLUMN task_review.reviewer_id IS '审核人账号 ID';
COMMENT ON COLUMN task_review.decision IS '决定：APPROVED/REJECTED';
COMMENT ON COLUMN task_review.reason IS '审核原因';
COMMENT ON COLUMN task_review.idempotency_key IS '审核请求幂等键';
COMMENT ON COLUMN task_review.created_at IS '创建时间';

CREATE UNIQUE INDEX uk_review_attempt ON task_review (attempt_id);
CREATE INDEX idx_review_assignment ON task_review (assignment_id);
CREATE INDEX idx_review_reviewer ON task_review (reviewer_id);
CREATE INDEX idx_review_decision ON task_review (decision);
