-- V6__points_tables.sql
-- CuteGoals 2.0 积分流水与余额表
-- ⚡ 并发/幂等/事务边界

-- 积分流水表（不可变 - 无 updated_at）
CREATE TABLE IF NOT EXISTS points_ledger (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id            BIGINT          NOT NULL,
    type                VARCHAR(10)     NOT NULL,
    amount              INT             NOT NULL,
    balance_after       INT             NOT NULL,
    business_ref        VARCHAR(255)    NOT NULL,
    source_snapshot     TEXT            DEFAULT NULL,
    operator_id         BIGINT          DEFAULT NULL,
    reason              VARCHAR(500)    DEFAULT NULL,
    refund_source_id    BIGINT          DEFAULT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ledger_child FOREIGN KEY (child_id) REFERENCES child_profile (id) ON DELETE CASCADE
);
COMMENT ON TABLE points_ledger IS '积分流水表（不可变）';
COMMENT ON COLUMN points_ledger.id IS '主键';
COMMENT ON COLUMN points_ledger.child_id IS '孩子 ID';
COMMENT ON COLUMN points_ledger.type IS '类型：EARN/SPEND/REFUND/ADJUST';
COMMENT ON COLUMN points_ledger.amount IS '金额（正数增加余额，负数减少）';
COMMENT ON COLUMN points_ledger.balance_after IS '变动后余额';
COMMENT ON COLUMN points_ledger.business_ref IS '唯一业务引用（来源类型+来源标识）';
COMMENT ON COLUMN points_ledger.source_snapshot IS '来源快照 JSON';
COMMENT ON COLUMN points_ledger.operator_id IS '操作者账号 ID';
COMMENT ON COLUMN points_ledger.reason IS '原因（调整必须填写）';
COMMENT ON COLUMN points_ledger.refund_source_id IS '退款来源流水 ID（唯一约束）';
COMMENT ON COLUMN points_ledger.created_at IS '创建时间';

CREATE UNIQUE INDEX uk_ledger_business_ref ON points_ledger (child_id, business_ref);
CREATE UNIQUE INDEX uk_ledger_refund_source ON points_ledger (refund_source_id);
CREATE INDEX idx_ledger_child ON points_ledger (child_id);
CREATE INDEX idx_ledger_type ON points_ledger (child_id, type);
CREATE INDEX idx_ledger_created ON points_ledger (child_id, created_at);
CREATE INDEX idx_ledger_business_ref ON points_ledger (business_ref);

-- 积分余额表（含乐观锁 version）
CREATE TABLE IF NOT EXISTS points_balance (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id        BIGINT          NOT NULL,
    balance         INT             NOT NULL DEFAULT 0,
    total_earned    INT             NOT NULL DEFAULT 0,
    version         INT             NOT NULL DEFAULT 0,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_balance_child FOREIGN KEY (child_id) REFERENCES child_profile (id) ON DELETE CASCADE
);
COMMENT ON TABLE points_balance IS '积分余额表';
COMMENT ON COLUMN points_balance.id IS '主键';
COMMENT ON COLUMN points_balance.child_id IS '孩子 ID（一对一）';
COMMENT ON COLUMN points_balance.balance IS '当前可用余额';
COMMENT ON COLUMN points_balance.total_earned IS '累计获得积分（仅 EARN 类型之和）';
COMMENT ON COLUMN points_balance.version IS '乐观锁版本号';
COMMENT ON COLUMN points_balance.created_at IS '创建时间';
COMMENT ON COLUMN points_balance.updated_at IS '更新时间';

CREATE UNIQUE INDEX uk_balance_child ON points_balance (child_id);
