-- V7__prize_blindbox_exchange_tables.sql
-- CuteGoals 2.0 奖品、盲盒与兑换表
-- ⚡ 并发/幂等/事务边界

-- 奖品表
CREATE TABLE IF NOT EXISTS prize (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id       BIGINT          NOT NULL,
    name            VARCHAR(100)    NOT NULL,
    description     VARCHAR(2000)   DEFAULT NULL,
    image           VARCHAR(500)    DEFAULT NULL,
    points_cost     INT             NOT NULL,
    stock           INT             NOT NULL DEFAULT 0,
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP       DEFAULT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prize_family FOREIGN KEY (family_id) REFERENCES family (id) ON DELETE CASCADE
);
COMMENT ON TABLE prize IS '奖品表';
COMMENT ON COLUMN prize.id IS '主键';
COMMENT ON COLUMN prize.family_id IS '家庭 ID';
COMMENT ON COLUMN prize.name IS '奖品名称';
COMMENT ON COLUMN prize.description IS '奖品描述';
COMMENT ON COLUMN prize.image IS '奖品图片';
COMMENT ON COLUMN prize.points_cost IS '积分价格（正整数）';
COMMENT ON COLUMN prize.stock IS '库存（非负整数）';
COMMENT ON COLUMN prize.enabled IS '是否启用';
COMMENT ON COLUMN prize.deleted IS '是否逻辑删除';
COMMENT ON COLUMN prize.deleted_at IS '删除时间';
COMMENT ON COLUMN prize.created_at IS '创建时间';
COMMENT ON COLUMN prize.updated_at IS '更新时间';

CREATE INDEX idx_prize_family ON prize (family_id);
CREATE INDEX idx_prize_status ON prize (family_id, enabled, deleted);

-- 盲盒奖池表
CREATE TABLE IF NOT EXISTS blind_box_pool (
    id                      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id               BIGINT          NOT NULL,
    name                    VARCHAR(100)    NOT NULL,
    description             VARCHAR(2000)   DEFAULT NULL,
    cost_points             INT             NOT NULL,
    enabled                 BOOLEAN         NOT NULL DEFAULT TRUE,
    deleted                 BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at              TIMESTAMP       DEFAULT NULL,
    availability_version    VARCHAR(64)     DEFAULT NULL,
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_blindbox_family FOREIGN KEY (family_id) REFERENCES family (id) ON DELETE CASCADE
);
COMMENT ON TABLE blind_box_pool IS '盲盒奖池表';
COMMENT ON COLUMN blind_box_pool.id IS '主键';
COMMENT ON COLUMN blind_box_pool.family_id IS '家庭 ID';
COMMENT ON COLUMN blind_box_pool.name IS '奖池名称';
COMMENT ON COLUMN blind_box_pool.description IS '奖池描述';
COMMENT ON COLUMN blind_box_pool.cost_points IS '兑换所需积分（正整数）';
COMMENT ON COLUMN blind_box_pool.enabled IS '是否启用';
COMMENT ON COLUMN blind_box_pool.deleted IS '是否逻辑删除';
COMMENT ON COLUMN blind_box_pool.deleted_at IS '删除时间';
COMMENT ON COLUMN blind_box_pool.availability_version IS '可用性版本哈希（SHA-256）';
COMMENT ON COLUMN blind_box_pool.created_at IS '创建时间';
COMMENT ON COLUMN blind_box_pool.updated_at IS '更新时间';

CREATE INDEX idx_blindbox_family ON blind_box_pool (family_id);
CREATE INDEX idx_blindbox_status ON blind_box_pool (family_id, enabled, deleted);

-- 盲盒奖品项表
CREATE TABLE IF NOT EXISTS blind_box_item (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pool_id         BIGINT          NOT NULL,
    prize_id        BIGINT          NOT NULL,
    weight          INT             NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_blindbox_item_pool FOREIGN KEY (pool_id) REFERENCES blind_box_pool (id) ON DELETE CASCADE,
    CONSTRAINT fk_blindbox_item_prize FOREIGN KEY (prize_id) REFERENCES prize (id) ON DELETE CASCADE
);
COMMENT ON TABLE blind_box_item IS '盲盒奖品项表';
COMMENT ON COLUMN blind_box_item.id IS '主键';
COMMENT ON COLUMN blind_box_item.pool_id IS '奖池 ID';
COMMENT ON COLUMN blind_box_item.prize_id IS '奖品 ID';
COMMENT ON COLUMN blind_box_item.weight IS '相对权重（正整数）';
COMMENT ON COLUMN blind_box_item.created_at IS '创建时间';

CREATE UNIQUE INDEX uk_blindbox_item ON blind_box_item (pool_id, prize_id);
CREATE INDEX idx_blindbox_item_prize ON blind_box_item (prize_id);

-- 兑换记录表
CREATE TABLE IF NOT EXISTS exchange (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id            BIGINT          NOT NULL,
    family_id           BIGINT          NOT NULL,
    type                VARCHAR(10)     NOT NULL,
    status              VARCHAR(30)     NOT NULL DEFAULT 'PENDING_FULFILLMENT',
    cost_points         INT             NOT NULL,
    idempotency_key     VARCHAR(128)    NOT NULL,
    prize_id            BIGINT          DEFAULT NULL,
    pool_id             BIGINT          DEFAULT NULL,
    result_prize_id     BIGINT          DEFAULT NULL,
    fulfilled_at        TIMESTAMP       DEFAULT NULL,
    fulfilled_by        BIGINT          DEFAULT NULL,
    cancelled_at        TIMESTAMP       DEFAULT NULL,
    cancelled_by        BIGINT          DEFAULT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exchange_child FOREIGN KEY (child_id) REFERENCES child_profile (id) ON DELETE CASCADE,
    CONSTRAINT fk_exchange_family FOREIGN KEY (family_id) REFERENCES family (id) ON DELETE CASCADE
);
COMMENT ON TABLE exchange IS '兑换记录表';
COMMENT ON COLUMN exchange.id IS '主键';
COMMENT ON COLUMN exchange.child_id IS '孩子 ID';
COMMENT ON COLUMN exchange.family_id IS '家庭 ID';
COMMENT ON COLUMN exchange.type IS '类型：DIRECT/BLIND_BOX';
COMMENT ON COLUMN exchange.status IS '状态：PENDING_FULFILLMENT/FULFILLED/CANCELLED/REFUNDED';
COMMENT ON COLUMN exchange.cost_points IS '实际消耗积分';
COMMENT ON COLUMN exchange.idempotency_key IS '幂等键';
COMMENT ON COLUMN exchange.prize_id IS '奖品 ID（直接兑换）';
COMMENT ON COLUMN exchange.pool_id IS '奖池 ID（盲盒兑换）';
COMMENT ON COLUMN exchange.result_prize_id IS '抽中奖品 ID（盲盒）';
COMMENT ON COLUMN exchange.fulfilled_at IS '兑现时间';
COMMENT ON COLUMN exchange.fulfilled_by IS '兑现人';
COMMENT ON COLUMN exchange.cancelled_at IS '取消时间';
COMMENT ON COLUMN exchange.cancelled_by IS '取消人';
COMMENT ON COLUMN exchange.created_at IS '创建时间';
COMMENT ON COLUMN exchange.updated_at IS '更新时间';

CREATE UNIQUE INDEX uk_exchange_idempotency ON exchange (child_id, idempotency_key);
CREATE INDEX idx_exchange_family ON exchange (family_id);
CREATE INDEX idx_exchange_child ON exchange (child_id);
CREATE INDEX idx_exchange_status ON exchange (status);
CREATE INDEX idx_exchange_created ON exchange (child_id, created_at);

-- 兑换快照表（不可变 - 无 updated_at）
CREATE TABLE IF NOT EXISTS exchange_snapshot (
    id                      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange_id             BIGINT          NOT NULL,
    prize_name              VARCHAR(100)    DEFAULT NULL,
    prize_image             VARCHAR(500)    DEFAULT NULL,
    prize_description       VARCHAR(2000)   DEFAULT NULL,
    points_cost             INT             DEFAULT NULL,
    pool_name               VARCHAR(100)    DEFAULT NULL,
    pool_cost_points        INT             DEFAULT NULL,
    availability_version    VARCHAR(64)     DEFAULT NULL,
    candidate_probabilities TEXT            DEFAULT NULL,
    drawn_prize_name        VARCHAR(100)    DEFAULT NULL,
    drawn_prize_image       VARCHAR(500)    DEFAULT NULL,
    drawn_probability       NUMERIC(5,2)    DEFAULT NULL,
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_snapshot_exchange FOREIGN KEY (exchange_id) REFERENCES exchange (id) ON DELETE CASCADE
);
COMMENT ON TABLE exchange_snapshot IS '兑换快照表（不可变）';
COMMENT ON COLUMN exchange_snapshot.id IS '主键';
COMMENT ON COLUMN exchange_snapshot.exchange_id IS '兑换 ID（一对一）';
COMMENT ON COLUMN exchange_snapshot.prize_name IS '奖品名称（兑换时）';
COMMENT ON COLUMN exchange_snapshot.prize_image IS '奖品图片（兑换时）';
COMMENT ON COLUMN exchange_snapshot.prize_description IS '奖品描述（兑换时）';
COMMENT ON COLUMN exchange_snapshot.points_cost IS '积分价格（兑换时）';
COMMENT ON COLUMN exchange_snapshot.pool_name IS '奖池名称（盲盒兑换时）';
COMMENT ON COLUMN exchange_snapshot.pool_cost_points IS '奖池成本（盲盒兑换时）';
COMMENT ON COLUMN exchange_snapshot.availability_version IS '确认时的可用性版本';
COMMENT ON COLUMN exchange_snapshot.candidate_probabilities IS '候选集概率 JSON';
COMMENT ON COLUMN exchange_snapshot.drawn_prize_name IS '抽中奖品名称（盲盒）';
COMMENT ON COLUMN exchange_snapshot.drawn_prize_image IS '抽中奖品图片（盲盒）';
COMMENT ON COLUMN exchange_snapshot.drawn_probability IS '抽中概率（盲盒）';
COMMENT ON COLUMN exchange_snapshot.created_at IS '创建时间';

CREATE UNIQUE INDEX uk_snapshot_exchange ON exchange_snapshot (exchange_id);
