-- V8__instance_management_and_audit_tables.sql
-- CuteGoals 2.0 实例管理与审计表
-- 🔒 安全敏感任务

-- 实例配置表
CREATE TABLE IF NOT EXISTS instance_config (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key      VARCHAR(100)    NOT NULL,
    config_value    TEXT            DEFAULT NULL,
    masked          BOOLEAN         NOT NULL DEFAULT FALSE,
    description     VARCHAR(500)    DEFAULT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE instance_config IS '实例配置表';
COMMENT ON COLUMN instance_config.id IS '主键';
COMMENT ON COLUMN instance_config.config_key IS '配置键';
COMMENT ON COLUMN instance_config.config_value IS '配置值（秘密字段以掩码存储）';
COMMENT ON COLUMN instance_config.masked IS '是否为脱敏秘密字段';
COMMENT ON COLUMN instance_config.description IS '配置说明';
COMMENT ON COLUMN instance_config.created_at IS '创建时间';
COMMENT ON COLUMN instance_config.updated_at IS '更新时间';

CREATE UNIQUE INDEX uk_config_key ON instance_config (config_key);

-- 审计日志表
CREATE TABLE IF NOT EXISTS audit_log (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id        BIGINT          DEFAULT NULL,
    actor_type      VARCHAR(20)     DEFAULT NULL,
    event_type      VARCHAR(50)     NOT NULL,
    result          VARCHAR(10)     NOT NULL,
    object_type     VARCHAR(50)     DEFAULT NULL,
    object_id       VARCHAR(100)    DEFAULT NULL,
    summary         VARCHAR(2000)   DEFAULT NULL,
    request_id      VARCHAR(128)    DEFAULT NULL,
    metadata        TEXT            DEFAULT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE audit_log IS '审计日志表';
COMMENT ON COLUMN audit_log.id IS '主键';
COMMENT ON COLUMN audit_log.actor_id IS '操作者 ID';
COMMENT ON COLUMN audit_log.actor_type IS '操作者类型';
COMMENT ON COLUMN audit_log.event_type IS '事件类型';
COMMENT ON COLUMN audit_log.result IS '结果：SUCCESS/FAILURE';
COMMENT ON COLUMN audit_log.object_type IS '对象类型';
COMMENT ON COLUMN audit_log.object_id IS '对象标识';
COMMENT ON COLUMN audit_log.summary IS '变更摘要（脱敏）';
COMMENT ON COLUMN audit_log.request_id IS '请求关联标识';
COMMENT ON COLUMN audit_log.metadata IS '额外元数据 JSON';
COMMENT ON COLUMN audit_log.created_at IS '创建时间';

CREATE INDEX idx_audit_actor_event ON audit_log (actor_id, event_type, created_at);
CREATE INDEX idx_audit_event_time ON audit_log (event_type, created_at);
CREATE INDEX idx_audit_object ON audit_log (object_type, object_id);
CREATE INDEX idx_audit_created ON audit_log (created_at);

-- 备份运行记录表
CREATE TABLE IF NOT EXISTS backup_run (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at          TIMESTAMP       NOT NULL,
    completed_at        TIMESTAMP       DEFAULT NULL,
    status              VARCHAR(20)     NOT NULL,
    size_bytes          BIGINT          DEFAULT NULL,
    checksum            VARCHAR(64)     DEFAULT NULL,
    app_version         VARCHAR(50)     DEFAULT NULL,
    schema_version      VARCHAR(50)     DEFAULT NULL,
    error_message       VARCHAR(2000)   DEFAULT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE backup_run IS '备份运行记录表';
COMMENT ON COLUMN backup_run.id IS '主键';
COMMENT ON COLUMN backup_run.started_at IS '备份开始时间';
COMMENT ON COLUMN backup_run.completed_at IS '备份完成时间';
COMMENT ON COLUMN backup_run.status IS '状态：RUNNING/SUCCESS/FAILED';
COMMENT ON COLUMN backup_run.size_bytes IS '备份大小（字节）';
COMMENT ON COLUMN backup_run.checksum IS '备份校验和';
COMMENT ON COLUMN backup_run.app_version IS '应用版本';
COMMENT ON COLUMN backup_run.schema_version IS '数据库 schema 版本';
COMMENT ON COLUMN backup_run.error_message IS '错误信息';
COMMENT ON COLUMN backup_run.created_at IS '创建时间';
COMMENT ON COLUMN backup_run.updated_at IS '更新时间';

CREATE INDEX idx_backup_status ON backup_run (status);
CREATE INDEX idx_backup_started ON backup_run (started_at);

-- 恢复演练结果表
CREATE TABLE IF NOT EXISTS recovery_drill (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at          TIMESTAMP       NOT NULL,
    completed_at        TIMESTAMP       DEFAULT NULL,
    success             BOOLEAN         NOT NULL,
    rpo_seconds         INT             DEFAULT NULL,
    rto_seconds         INT             DEFAULT NULL,
    backup_used         VARCHAR(255)    DEFAULT NULL,
    details             TEXT            DEFAULT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE recovery_drill IS '恢复演练结果表';
COMMENT ON COLUMN recovery_drill.id IS '主键';
COMMENT ON COLUMN recovery_drill.started_at IS '演练开始时间';
COMMENT ON COLUMN recovery_drill.completed_at IS '演练完成时间';
COMMENT ON COLUMN recovery_drill.success IS '是否成功';
COMMENT ON COLUMN recovery_drill.rpo_seconds IS '实际 RPO（秒）';
COMMENT ON COLUMN recovery_drill.rto_seconds IS '实际 RTO（秒）';
COMMENT ON COLUMN recovery_drill.backup_used IS '使用的备份标识';
COMMENT ON COLUMN recovery_drill.details IS '演练详情';
COMMENT ON COLUMN recovery_drill.created_at IS '创建时间';

CREATE INDEX idx_drill_success ON recovery_drill (success);
CREATE INDEX idx_drill_started ON recovery_drill (started_at);
