package com.cutegoals.common.exception;

/**
 * Unified error codes for the CuteGoals API.
 * Format: {@code <CAPABILITY>_<REASON>}.
 */
public enum ErrorCode {

    // === General ===
    INTERNAL_ERROR("INTERNAL_ERROR"),
    RATE_LIMITED("RATE_LIMITED"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    NOT_FOUND("NOT_FOUND"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    VALIDATION_FAILED("VALIDATION_FAILED"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),

    // === Auth (AUTH_) ===
    AUTHENTICATION_FAILED("AUTHENTICATION_FAILED"),
    INITIALIZATION_NOT_ALLOWED("INITIALIZATION_NOT_ALLOWED"),
    SMS_LOGIN_NOT_CONFIGURED("SMS_LOGIN_NOT_CONFIGURED"),
    REFRESH_TOKEN_INVALID("REFRESH_TOKEN_INVALID"),
    REFRESH_TOKEN_REUSED("REFRESH_TOKEN_REUSED"),
    SESSION_REVOKED("SESSION_REVOKED"),
    RECOVERY_NOT_AVAILABLE("RECOVERY_NOT_AVAILABLE"),
    PASSWORD_POLICY_VIOLATED("PASSWORD_POLICY_VIOLATED"),

    // === Instance Management (INSTANCE_MANAGEMENT_) ===
    CAPABILITY_NOT_SUPPORTED("CAPABILITY_NOT_SUPPORTED"),
    CONFIGURATION_INVALID("CONFIGURATION_INVALID"),
    LAST_INSTANCE_ADMIN("LAST_INSTANCE_ADMIN"),
    LAST_ACTIVE_PARENT("LAST_ACTIVE_PARENT"),
    AUDIT_IMMUTABLE("AUDIT_IMMUTABLE"),
    AUDIT_QUERY_LIMIT_EXCEEDED("AUDIT_QUERY_LIMIT_EXCEEDED"),
    CONFIG_INVALID("CONFIG_INVALID"),

    // === Family (FAMILY_) ===
    SINGLE_FAMILY_ONLY("SINGLE_FAMILY_ONLY"),
    INVITATION_NOT_AVAILABLE("INVITATION_NOT_AVAILABLE"),
    PIN_CONFLICT("PIN_CONFLICT"),
    DEVICE_BINDING_NOT_AVAILABLE("DEVICE_BINDING_NOT_AVAILABLE"),
    AUDIT_UNAVAILABLE("AUDIT_UNAVAILABLE"),

    // === Child auth ===
    DEVICE_NOT_AUTHORIZED("DEVICE_NOT_AUTHORIZED"),
    CHILD_AUTHENTICATION_FAILED("CHILD_AUTHENTICATION_FAILED"),
    PIN_LOCKED("PIN_LOCKED"),

    // === Task Template (TASK_TEMPLATE_) ===
    TASK_TEMPLATE_FORBIDDEN("TASK_TEMPLATE_FORBIDDEN"),
    TASK_TEMPLATE_NOT_FOUND("TASK_TEMPLATE_NOT_FOUND"),
    TASK_TEMPLATE_VALIDATION_FAILED("TASK_TEMPLATE_VALIDATION_FAILED"),
    TASK_TEMPLATE_INVALID_RECURRENCE("TASK_TEMPLATE_INVALID_RECURRENCE"),
    TASK_TEMPLATE_REQUIRES_ACTIVE_DIFFICULTY("TASK_TEMPLATE_REQUIRES_ACTIVE_DIFFICULTY"),
    TASK_TEMPLATE_VERSION_CONFLICT("TASK_TEMPLATE_VERSION_CONFLICT"),
    TASK_TEMPLATE_INACTIVE("TASK_TEMPLATE_INACTIVE"),
    TASK_TEMPLATE_INVALID_QUERY("TASK_TEMPLATE_INVALID_QUERY"),

    // === Task Assignment (TASK_ASSIGNMENT_) ===
    TASK_ASSIGNMENT_FORBIDDEN("TASK_ASSIGNMENT_FORBIDDEN"),
    TASK_ASSIGNMENT_NOT_FOUND("TASK_ASSIGNMENT_NOT_FOUND"),
    TASK_ASSIGNMENT_TEMPLATE_INACTIVE("TASK_ASSIGNMENT_TEMPLATE_INACTIVE"),
    TASK_ASSIGNMENT_DIFFICULTY_INACTIVE("TASK_ASSIGNMENT_DIFFICULTY_INACTIVE"),
    TASK_ASSIGNMENT_CHILD_NOT_FOUND("TASK_ASSIGNMENT_CHILD_NOT_FOUND"),
    TASK_ASSIGNMENT_INVALID_DEADLINE("TASK_ASSIGNMENT_INVALID_DEADLINE"),
    TASK_ASSIGNMENT_IDEMPOTENCY_CONFLICT("TASK_ASSIGNMENT_IDEMPOTENCY_CONFLICT"),
    TASK_ASSIGNMENT_INVALID_DATE_RANGE("TASK_ASSIGNMENT_INVALID_DATE_RANGE"),
    TASK_ASSIGNMENT_RECURRENCE_NOT_CONFIGURED("TASK_ASSIGNMENT_RECURRENCE_NOT_CONFIGURED"),
    TASK_ASSIGNMENT_NOT_EDITABLE("TASK_ASSIGNMENT_NOT_EDITABLE"),
    TASK_ASSIGNMENT_VERSION_CONFLICT("TASK_ASSIGNMENT_VERSION_CONFLICT"),
    TASK_ASSIGNMENT_ALREADY_APPROVED("TASK_ASSIGNMENT_ALREADY_APPROVED"),
    TASK_ASSIGNMENT_CANCELLED("TASK_ASSIGNMENT_CANCELLED"),
    TASK_ASSIGNMENT_INVALID_QUERY("TASK_ASSIGNMENT_INVALID_QUERY"),

    // === Task Review (TASK_REVIEW_) ===
    TASK_REVIEW_FORBIDDEN("TASK_REVIEW_FORBIDDEN"),
    TASK_REVIEW_NOT_FOUND("TASK_REVIEW_NOT_FOUND"),
    TASK_REVIEW_INVALID_STATE("TASK_REVIEW_INVALID_STATE"),
    TASK_REVIEW_REASON_REQUIRED("TASK_REVIEW_REASON_REQUIRED"),
    TASK_REVIEW_VALIDATION_FAILED("TASK_REVIEW_VALIDATION_FAILED"),
    TASK_REVIEW_ALREADY_DECIDED("TASK_REVIEW_ALREADY_DECIDED"),
    TASK_REVIEW_STALE_ATTEMPT("TASK_REVIEW_STALE_ATTEMPT"),
    TASK_REVIEW_IDEMPOTENCY_CONFLICT("TASK_REVIEW_IDEMPOTENCY_CONFLICT"),
    TASK_REVIEW_INVALID_QUERY("TASK_REVIEW_INVALID_QUERY"),
    TASK_REVIEW_HISTORY_IMMUTABLE("TASK_REVIEW_HISTORY_IMMUTABLE"),

    // === Task Submission (TASK_SUBMISSION_) ===
    TASK_SUBMISSION_VALIDATION_FAILED("TASK_SUBMISSION_VALIDATION_FAILED"),
    TASK_SUBMISSION_LATE_NOT_ALLOWED("TASK_SUBMISSION_LATE_NOT_ALLOWED"),
    TASK_SUBMISSION_IDEMPOTENCY_CONFLICT("TASK_SUBMISSION_IDEMPOTENCY_CONFLICT"),

    // === Points (POINTS_) ===
    POINTS_FORBIDDEN("POINTS_FORBIDDEN"),
    POINTS_ACCOUNT_NOT_FOUND("POINTS_ACCOUNT_NOT_FOUND"),
    POINTS_INVALID_TRANSACTION("POINTS_INVALID_TRANSACTION"),
    POINTS_INSUFFICIENT_BALANCE("POINTS_INSUFFICIENT_BALANCE"),
    POINTS_ACCOUNT_CONFLICT("POINTS_ACCOUNT_CONFLICT"),
    POINTS_ADJUST_REASON_REQUIRED("POINTS_ADJUST_REASON_REQUIRED"),
    POINTS_REFERENCE_CONFLICT("POINTS_REFERENCE_CONFLICT"),
    POINTS_LEDGER_IMMUTABLE("POINTS_LEDGER_IMMUTABLE"),
    POINTS_REFUND_SOURCE_INVALID("POINTS_REFUND_SOURCE_INVALID"),
    POINTS_ALREADY_REFUNDED("POINTS_ALREADY_REFUNDED"),
    POINTS_SPEND_SOURCE_INVALID("POINTS_SPEND_SOURCE_INVALID"),
    POINTS_INVALID_QUERY("POINTS_INVALID_QUERY");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    @Override
    public String toString() {
        return code;
    }
}
