package com.cutegoals.common.exception;

/**
 * Unified error codes for the CuteGoals API.
 * Format: {@code <CAPABILITY>_<REASON>}.
 */
public enum ErrorCode {

    // === General ===
    INTERNAL_ERROR("INTERNAL_ERROR"),
    RATE_LIMITED("RATE_LIMITED"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    NOT_FOUND("NOT_FOUND"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    VALIDATION_FAILED("VALIDATION_FAILED"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),

    // === Auth (AUTH_) ===
    AUTHENTICATION_FAILED("AUTHENTICATION_FAILED"),
    INITIALIZATION_NOT_ALLOWED("INITIALIZATION_NOT_ALLOWED"),
    SMS_LOGIN_NOT_CONFIGURED("SMS_LOGIN_NOT_CONFIGURED"),
    REFRESH_TOKEN_INVALID("REFRESH_TOKEN_INVALID"),
    REFRESH_TOKEN_REUSED("REFRESH_TOKEN_REUSED"),
    SESSION_REVOKED("SESSION_REVOKED"),
    RECOVERY_NOT_AVAILABLE("RECOVERY_NOT_AVAILABLE"),
    PASSWORD_POLICY_VIOLATED("PASSWORD_POLICY_VIOLATED"),

    // === Instance Management (INSTANCE_MANAGEMENT_) ===
    CAPABILITY_NOT_SUPPORTED("CAPABILITY_NOT_SUPPORTED"),
    CONFIGURATION_INVALID("CONFIGURATION_INVALID"),
    LAST_INSTANCE_ADMIN("LAST_INSTANCE_ADMIN"),
    LAST_ACTIVE_PARENT("LAST_ACTIVE_PARENT"),
    AUDIT_IMMUTABLE("AUDIT_IMMUTABLE"),
    AUDIT_QUERY_LIMIT_EXCEEDED("AUDIT_QUERY_LIMIT_EXCEEDED"),
    CONFIG_INVALID("CONFIG_INVALID"),

    // === Family (FAMILY_) ===
    SINGLE_FAMILY_ONLY("SINGLE_FAMILY_ONLY"),
    INVITATION_NOT_AVAILABLE("INVITATION_NOT_AVAILABLE"),
    PIN_CONFLICT("PIN_CONFLICT"),
    DEVICE_BINDING_NOT_AVAILABLE("DEVICE_BINDING_NOT_AVAILABLE"),
    AUDIT_UNAVAILABLE("AUDIT_UNAVAILABLE"),

    // === Child auth ===
    DEVICE_NOT_AUTHORIZED("DEVICE_NOT_AUTHORIZED"),
    CHILD_AUTHENTICATION_FAILED("CHILD_AUTHENTICATION_FAILED"),
    PIN_LOCKED("PIN_LOCKED");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    @Override
    public String toString() {
        return code;
    }
}
