/** Stable error codes as defined in design doc §5.2 */

export const ErrorCodes = {
  // POINTS
  POINTS_FORBIDDEN: 'POINTS_FORBIDDEN',
  POINTS_ACCOUNT_NOT_FOUND: 'POINTS_ACCOUNT_NOT_FOUND',
  POINTS_INVALID_TRANSACTION: 'POINTS_INVALID_TRANSACTION',
  POINTS_LEDGER_IMMUTABLE: 'POINTS_LEDGER_IMMUTABLE',
  POINTS_REFERENCE_CONFLICT: 'POINTS_REFERENCE_CONFLICT',
  POINTS_INSUFFICIENT_BALANCE: 'POINTS_INSUFFICIENT_BALANCE',
  POINTS_ACCOUNT_CONFLICT: 'POINTS_ACCOUNT_CONFLICT',
  POINTS_SPEND_SOURCE_INVALID: 'POINTS_SPEND_SOURCE_INVALID',
  POINTS_ALREADY_REFUNDED: 'POINTS_ALREADY_REFUNDED',
  POINTS_ADJUST_REASON_REQUIRED: 'POINTS_ADJUST_REASON_REQUIRED',
  POINTS_REFUND_SOURCE_INVALID: 'POINTS_REFUND_SOURCE_INVALID',
  POINTS_INVALID_QUERY: 'POINTS_INVALID_QUERY',

  // EXCHANGE
  EXCHANGE_IDEMPOTENCY_KEY_REQUIRED: 'EXCHANGE_IDEMPOTENCY_KEY_REQUIRED',
  EXCHANGE_IDEMPOTENCY_CONFLICT: 'EXCHANGE_IDEMPOTENCY_CONFLICT',
  EXCHANGE_INVALID_STATE: 'EXCHANGE_INVALID_STATE',
  EXCHANGE_TRANSACTION_FAILED: 'EXCHANGE_TRANSACTION_FAILED',
  EXCHANGE_CANCELLATION_FAILED: 'EXCHANGE_CANCELLATION_FAILED',
  EXCHANGE_NOT_FOUND: 'EXCHANGE_NOT_FOUND',
  EXCHANGE_INVALID_QUERY: 'EXCHANGE_INVALID_QUERY',

  // TASK_TEMPLATE
  TASK_TEMPLATE_FORBIDDEN: 'TASK_TEMPLATE_FORBIDDEN',
  TASK_TEMPLATE_NOT_FOUND: 'TASK_TEMPLATE_NOT_FOUND',
  TASK_TEMPLATE_VALIDATION_FAILED: 'TASK_TEMPLATE_VALIDATION_FAILED',
  TASK_TEMPLATE_REQUIRES_ACTIVE_DIFFICULTY: 'TASK_TEMPLATE_REQUIRES_ACTIVE_DIFFICULTY',
  TASK_TEMPLATE_INVALID_RECURRENCE: 'TASK_TEMPLATE_INVALID_RECURRENCE',
  TASK_TEMPLATE_VERSION_CONFLICT: 'TASK_TEMPLATE_VERSION_CONFLICT',
  TASK_TEMPLATE_INACTIVE: 'TASK_TEMPLATE_INACTIVE',
  TASK_TEMPLATE_TYPE_IMMUTABLE: 'TASK_TEMPLATE_TYPE_IMMUTABLE',
  TASK_TEMPLATE_TYPE_CONFIG_MISMATCH: 'TASK_TEMPLATE_TYPE_CONFIG_MISMATCH',
  TASK_TEMPLATE_INVALID_QUERY: 'TASK_TEMPLATE_INVALID_QUERY',

  // TASK_LIMITED
  TASK_LIMITED_NOT_STARTED: 'TASK_LIMITED_NOT_STARTED',
  TASK_LIMITED_EXPIRED: 'TASK_LIMITED_EXPIRED',

  // TASK_REPEAT
  TASK_REPEAT_NOT_TRIGGER_DAY: 'TASK_REPEAT_NOT_TRIGGER_DAY',

  // TASK_STANDING
  TASK_STANDING_LIMIT_REACHED: 'TASK_STANDING_LIMIT_REACHED',

  // TASK_ASSIGNMENT
  TASK_ASSIGNMENT_FORBIDDEN: 'TASK_ASSIGNMENT_FORBIDDEN',
  TASK_ASSIGNMENT_NOT_FOUND: 'TASK_ASSIGNMENT_NOT_FOUND',
  TASK_ASSIGNMENT_DIFFICULTY_INACTIVE: 'TASK_ASSIGNMENT_DIFFICULTY_INACTIVE',
  TASK_ASSIGNMENT_TEMPLATE_INACTIVE: 'TASK_ASSIGNMENT_TEMPLATE_INACTIVE',
  TASK_ASSIGNMENT_CHILD_NOT_FOUND: 'TASK_ASSIGNMENT_CHILD_NOT_FOUND',
  TASK_ASSIGNMENT_INVALID_DEADLINE: 'TASK_ASSIGNMENT_INVALID_DEADLINE',
  TASK_ASSIGNMENT_IDEMPOTENCY_CONFLICT: 'TASK_ASSIGNMENT_IDEMPOTENCY_CONFLICT',
  TASK_ASSIGNMENT_INVALID_DATE_RANGE: 'TASK_ASSIGNMENT_INVALID_DATE_RANGE',
  TASK_ASSIGNMENT_RECURRENCE_NOT_CONFIGURED: 'TASK_ASSIGNMENT_RECURRENCE_NOT_CONFIGURED',
  TASK_ASSIGNMENT_VERSION_CONFLICT: 'TASK_ASSIGNMENT_VERSION_CONFLICT',
  TASK_ASSIGNMENT_NOT_EDITABLE: 'TASK_ASSIGNMENT_NOT_EDITABLE',
  TASK_ASSIGNMENT_ALREADY_APPROVED: 'TASK_ASSIGNMENT_ALREADY_APPROVED',
  TASK_ASSIGNMENT_INVALID_QUERY: 'TASK_ASSIGNMENT_INVALID_QUERY',

  // TASK_REVIEW
  TASK_REVIEW_FORBIDDEN: 'TASK_REVIEW_FORBIDDEN',
  TASK_REVIEW_NOT_FOUND: 'TASK_REVIEW_NOT_FOUND',
  TASK_SUBMISSION_VALIDATION_FAILED: 'TASK_SUBMISSION_VALIDATION_FAILED',
  TASK_REVIEW_INVALID_STATE: 'TASK_REVIEW_INVALID_STATE',
  TASK_SUBMISSION_IDEMPOTENCY_CONFLICT: 'TASK_SUBMISSION_IDEMPOTENCY_CONFLICT',
  TASK_SUBMISSION_LATE_NOT_ALLOWED: 'TASK_SUBMISSION_LATE_NOT_ALLOWED',
  TASK_REVIEW_REASON_REQUIRED: 'TASK_REVIEW_REASON_REQUIRED',
  TASK_REVIEW_VALIDATION_FAILED: 'TASK_REVIEW_VALIDATION_FAILED',
  TASK_REVIEW_IDEMPOTENCY_CONFLICT: 'TASK_REVIEW_IDEMPOTENCY_CONFLICT',
  TASK_REVIEW_ALREADY_DECIDED: 'TASK_REVIEW_ALREADY_DECIDED',
  TASK_REVIEW_STALE_ATTEMPT: 'TASK_REVIEW_STALE_ATTEMPT',
  TASK_ASSIGNMENT_CANCELLED: 'TASK_ASSIGNMENT_CANCELLED',
  TASK_REVIEW_INVALID_QUERY: 'TASK_REVIEW_INVALID_QUERY',
  TASK_REVIEW_HISTORY_IMMUTABLE: 'TASK_REVIEW_HISTORY_IMMUTABLE',

  // PRIZE
  PRIZE_INVALID_POINTS_COST: 'PRIZE_INVALID_POINTS_COST',
  PRIZE_INVALID_STOCK: 'PRIZE_INVALID_STOCK',
  PRIZE_NOT_FOUND: 'PRIZE_NOT_FOUND',
  PRIZE_OUT_OF_STOCK: 'PRIZE_OUT_OF_STOCK',

  // BLIND_BOX
  BLIND_BOX_NOT_FOUND: 'BLIND_BOX_NOT_FOUND',
  BLIND_BOX_POOL_CHANGED: 'BLIND_BOX_POOL_CHANGED',
  BLIND_BOX_INVALID_COST: 'BLIND_BOX_INVALID_COST',
  BLIND_BOX_EMPTY_POOL: 'BLIND_BOX_EMPTY_POOL',
  BLIND_BOX_INVALID_WEIGHT: 'BLIND_BOX_INVALID_WEIGHT',
  BLIND_BOX_DUPLICATE_PRIZE: 'BLIND_BOX_DUPLICATE_PRIZE',
  BLIND_BOX_UNAVAILABLE: 'BLIND_BOX_UNAVAILABLE',

  // AUTH
  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  SMS_LOGIN_NOT_CONFIGURED: 'SMS_LOGIN_NOT_CONFIGURED',
  CHILD_AUTHENTICATION_FAILED: 'CHILD_AUTHENTICATION_FAILED',
  PIN_LOCKED: 'PIN_LOCKED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  SESSION_REVOKED: 'SESSION_REVOKED',
  DEVICE_NOT_AUTHORIZED: 'DEVICE_NOT_AUTHORIZED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // FAMILY
  SINGLE_FAMILY_ONLY: 'SINGLE_FAMILY_ONLY',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVITATION_NOT_AVAILABLE: 'INVITATION_NOT_AVAILABLE',
  LAST_ACTIVE_PARENT: 'LAST_ACTIVE_PARENT',
  PIN_CONFLICT: 'PIN_CONFLICT',
  DEVICE_BINDING_NOT_AVAILABLE: 'DEVICE_BINDING_NOT_AVAILABLE',
  AUDIT_UNAVAILABLE: 'AUDIT_UNAVAILABLE',

  // INSTANCE
  INSTANCE_ADMIN_REQUIRED: 'INSTANCE_ADMIN_REQUIRED',
  LAST_INSTANCE_ADMIN: 'LAST_INSTANCE_ADMIN',
  AUDIT_QUERY_LIMIT_EXCEEDED: 'AUDIT_QUERY_LIMIT_EXCEEDED',
  AUDIT_IMMUTABLE: 'AUDIT_IMMUTABLE',
  CONFIGURATION_INVALID: 'CONFIGURATION_INVALID',
  RECOVERY_NOT_AVAILABLE: 'RECOVERY_NOT_AVAILABLE',
  RPO_EXCEEDED: 'RPO_EXCEEDED',
  INITIALIZATION_NOT_ALLOWED: 'INITIALIZATION_NOT_ALLOWED',

  // DEPLOYMENT
  BUILD_DEPENDENCY_UNAVAILABLE: 'BUILD_DEPENDENCY_UNAVAILABLE',
  UNSUPPORTED_PLATFORM: 'UNSUPPORTED_PLATFORM',
  DEPENDENCY_UNHEALTHY: 'DEPENDENCY_UNHEALTHY',
  TLS_REQUIRED: 'TLS_REQUIRED',
  CONFIG_INVALID: 'CONFIG_INVALID',
  BACKUP_FAILED: 'BACKUP_FAILED',
  RESTORE_BACKUP_INVALID: 'RESTORE_BACKUP_INVALID',
  RESTORE_FAILED: 'RESTORE_FAILED',
  PRE_UPGRADE_BACKUP_FAILED: 'PRE_UPGRADE_BACKUP_FAILED',
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  UPGRADE_HEALTHCHECK_FAILED: 'UPGRADE_HEALTHCHECK_FAILED',
  DOWNGRADE_NOT_SUPPORTED: 'DOWNGRADE_NOT_SUPPORTED',

  // WEB_APP (UI-level error states)
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INSUFFICIENT_POINTS: 'INSUFFICIENT_POINTS',

  // General
  CAPABILITY_NOT_SUPPORTED: 'CAPABILITY_NOT_SUPPORTED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

/** 任务类型 */
export type TaskTypeValue = 'LIMITED' | 'REPEAT' | 'STANDING';

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/** Structured API error from the server */
export interface ApiError {
  /** Stable business error code */
  error_code: ErrorCode | string;
  /** Optional human-readable detail */
  message?: string;
  /** Optional request correlation id for debugging */
  id?: string;
  /** Optional additional context */
  details?: Record<string, unknown>;
}

/** Unified API response wrapper */
export interface ApiResponse<T = unknown> {
  data?: T;
  error?: ApiError;
}

/** Request configuration passed to the client methods */
export interface RequestConfig {
  /** HTTP method */
  method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  /** Request body */
  body?: unknown;
  /** Additional headers to merge */
  headers?: Record<string, string>;
  /** AbortSignal for cancellation */
  signal?: AbortSignal;
  /** Max retries on network error / 429 (default: 3) */
  maxRetries?: number;
}

/** Configuration for the ApiClient constructor */
export interface ApiClientConfig {
  /** Base URL for all requests (e.g. '/api/v1') */
  baseUrl: string;
  /** Called when a 401 response is received */
  onUnauthorized?: () => void;
  /** Called for every mapped error */
  onError?: (error: ApiError, httpStatus: number) => void;
  /** Base delay in ms for exponential backoff retry (default: 1000) */
  retryBaseDelayMs?: number;
}
