/** Stable error codes as defined in design doc §5.2 */

export const ErrorCodes = {
  // POINTS
  POINTS_FORBIDDEN: 'POINTS_FORBIDDEN',
  POINTS_ACCOUNT_NOT_FOUND: 'POINTS_ACCOUNT_NOT_FOUND',
  POINTS_INVALID_TRANSACTION: 'POINTS_INVALID_TRANSACTION',
  POINTS_LEDGER_IMMUTABLE: 'POINTS_LEDGER_IMMUTABLE',
  POINTS_REFERENCE_CONFLICT: 'POINTS_REFERENCE_CONFLICT',
  POINTS_INSUFFICIENT_BALANCE: 'POINTS_INSUFFICIENT_BALANCE',
  POINTS_ACCOUNT_CONFLICT: 'POINTS_ACCOUNT_CONFLICT',
  POINTS_SPEND_SOURCE_INVALID: 'POINTS_SPEND_SOURCE_INVALID',
  POINTS_ALREADY_REFUNDED: 'POINTS_ALREADY_REFUNDED',
  POINTS_ADJUST_REASON_REQUIRED: 'POINTS_ADJUST_REASON_REQUIRED',

  // EXCHANGE
  EXCHANGE_IDEMPOTENCY_KEY_REQUIRED: 'EXCHANGE_IDEMPOTENCY_KEY_REQUIRED',
  EXCHANGE_IDEMPOTENCY_CONFLICT: 'EXCHANGE_IDEMPOTENCY_CONFLICT',
  EXCHANGE_INVALID_STATE: 'EXCHANGE_INVALID_STATE',
  EXCHANGE_TRANSACTION_FAILED: 'EXCHANGE_TRANSACTION_FAILED',
  EXCHANGE_CANCELLATION_FAILED: 'EXCHANGE_CANCELLATION_FAILED',
  EXCHANGE_NOT_FOUND: 'EXCHANGE_NOT_FOUND',
  EXCHANGE_INVALID_QUERY: 'EXCHANGE_INVALID_QUERY',

  // TASK
  TASK_REVIEW_FORBIDDEN: 'TASK_REVIEW_FORBIDDEN',
  TASK_REVIEW_NOT_FOUND: 'TASK_REVIEW_NOT_FOUND',
  TASK_SUBMISSION_VALIDATION_FAILED: 'TASK_SUBMISSION_VALIDATION_FAILED',
  TASK_REVIEW_INVALID_STATE: 'TASK_REVIEW_INVALID_STATE',
  TASK_SUBMISSION_IDEMPOTENCY_CONFLICT: 'TASK_SUBMISSION_IDEMPOTENCY_CONFLICT',
  TASK_SUBMISSION_LATE_NOT_ALLOWED: 'TASK_SUBMISSION_LATE_NOT_ALLOWED',
  TASK_REVIEW_REASON_REQUIRED: 'TASK_REVIEW_REASON_REQUIRED',
  TASK_REVIEW_VALIDATION_FAILED: 'TASK_REVIEW_VALIDATION_FAILED',
  TASK_REVIEW_IDEMPOTENCY_CONFLICT: 'TASK_REVIEW_IDEMPOTENCY_CONFLICT',
  TASK_REVIEW_ALREADY_DECIDED: 'TASK_REVIEW_ALREADY_DECIDED',
  TASK_REVIEW_STALE_ATTEMPT: 'TASK_REVIEW_STALE_ATTEMPT',
  TASK_ASSIGNMENT_CANCELLED: 'TASK_ASSIGNMENT_CANCELLED',
  TASK_REVIEW_INVALID_QUERY: 'TASK_REVIEW_INVALID_QUERY',
  TASK_REVIEW_HISTORY_IMMUTABLE: 'TASK_REVIEW_HISTORY_IMMUTABLE',

  // PRIZE
  PRIZE_INVALID_POINTS_COST: 'PRIZE_INVALID_POINTS_COST',
  PRIZE_INVALID_STOCK: 'PRIZE_INVALID_STOCK',
  PRIZE_NOT_FOUND: 'PRIZE_NOT_FOUND',
  PRIZE_OUT_OF_STOCK: 'PRIZE_OUT_OF_STOCK',

  // BLIND_BOX
  BLIND_BOX_NOT_FOUND: 'BLIND_BOX_NOT_FOUND',
  BLIND_BOX_POOL_CHANGED: 'BLIND_BOX_POOL_CHANGED',

  // AUTH
  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',

  // INSTANCE
  INSTANCE_ADMIN_REQUIRED: 'INSTANCE_ADMIN_REQUIRED',
  LAST_INSTANCE_ADMIN: 'LAST_INSTANCE_ADMIN',
  AUDIT_QUERY_LIMIT_EXCEEDED: 'AUDIT_QUERY_LIMIT_EXCEEDED',

  // General
  CAPABILITY_NOT_SUPPORTED: 'CAPABILITY_NOT_SUPPORTED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/** Structured API error from the server */
export interface ApiError {
  /** Stable business error code */
  error_code: ErrorCode | string;
  /** Optional human-readable detail */
  message?: string;
  /** Optional request correlation id for debugging */
  id?: string;
  /** Optional additional context */
  details?: Record<string, unknown>;
}

/** Unified API response wrapper */
export interface ApiResponse<T = unknown> {
  data?: T;
  error?: ApiError;
}

/** Request configuration passed to the client methods */
export interface RequestConfig {
  /** HTTP method */
  method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  /** Request body */
  body?: unknown;
  /** Additional headers to merge */
  headers?: Record<string, string>;
  /** AbortSignal for cancellation */
  signal?: AbortSignal;
  /** Max retries on network error / 429 (default: 3) */
  maxRetries?: number;
}

/** Configuration for the ApiClient constructor */
export interface ApiClientConfig {
  /** Base URL for all requests (e.g. '/api/v1') */
  baseUrl: string;
  /** Called when a 401 response is received */
  onUnauthorized?: () => void;
  /** Called for every mapped error */
  onError?: (error: ApiError, httpStatus: number) => void;
  /** Base delay in ms for exponential backoff retry (default: 1000) */
  retryBaseDelayMs?: number;
}
