export default [
  {
    path: '/admin',
    component: '@/layouts/AdminLayout',
    routes: [
      { path: '/admin/init', component: '@/admin/pages/AdminInitPage' },
      { path: '/admin/login', component: '@/admin/pages/AdminLoginPage' },
      { path: '/admin', component: '@/admin/pages', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/admin/config', component: '@/admin/pages/AdminConfigPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/admin/accounts', component: '@/admin/pages/AdminAccountsPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/admin/audit', component: '@/admin/pages/AdminAuditPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/admin/health', component: '@/admin/pages/AdminHealthPage', wrappers: ['@/wrappers/AuthGuard'] },
    ],
  },
  {
    path: '/parent',
    component: '@/layouts/ParentLayout',
    routes: [
      { path: '/parent/login', component: '@/parent/pages/ParentLoginPage' },
      { path: '/parent', component: '@/parent/pages', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/parent/family', component: '@/parent/pages/ParentFamilyPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/parent/children', component: '@/parent/pages/ParentChildrenPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/parent/templates', component: '@/parent/pages/ParentTemplatesPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/parent/tasks', component: '@/parent/pages/ParentTasksPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/parent/reviews', component: '@/parent/pages/ParentReviewsPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/parent/points', component: '@/parent/pages/ParentPointsPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/parent/prizes', component: '@/parent/pages/ParentPrizesPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/parent/blind-boxes', component: '@/parent/pages/ParentBlindBoxesPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/parent/devices', component: '@/parent/pages/ParentDevicesPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/parent/exchanges', component: '@/parent/pages/ParentExchangesPage', wrappers: ['@/wrappers/AuthGuard'] },
    ],
  },
  {
    path: '/child',
    component: '@/layouts/ChildLayout',
    routes: [
      { path: '/child/bind', component: '@/child/pages/ChildBindPage' },
      { path: '/child/login', component: '@/child/pages/ChildLoginPage' },
      { path: '/child', component: '@/child/pages', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/child/tasks', component: '@/child/pages/ChildTasksPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/child/prizes', component: '@/child/pages/ChildPrizesPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/child/blind-boxes', component: '@/child/pages/ChildBlindBoxesPage', wrappers: ['@/wrappers/AuthGuard'] },
      { path: '/child/exchanges', component: '@/child/pages/ChildExchangesPage', wrappers: ['@/wrappers/AuthGuard'] },
    ],
  },
  { path: '/', redirect: '/parent' },
];
